# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1183, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(640, 60, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 0, 611, 651))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(255,255,255)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(760, 360, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("QPushButton#login_button{\n"
"    background-color:rgb(52, 128, 235);\n"
"    border:none;\n"
"    color:rgb(255,255,255);\n"
"    border-radius: 15px\n"
"}\n"
"QPushButton#login_button:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgb(19, 38, 99)\n"
"}")
        self.login_button.setAutoDefault(False)
        self.login_button.setObjectName("login_button")
        self.register_label = QtWidgets.QLabel(self.centralwidget)
        self.register_label.setGeometry(QtCore.QRect(740, 420, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.register_label.setFont(font)
        self.register_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.register_label.setObjectName("register_label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(640, 170, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.email_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.email_edit.setGeometry(QtCore.QRect(640, 190, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.email_edit.setFont(font)
        self.email_edit.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);")
        self.email_edit.setText("")
        self.email_edit.setPlaceholderText("")
        self.email_edit.setObjectName("email_edit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(640, 250, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.password_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_edit.setGeometry(QtCore.QRect(640, 270, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.password_edit.setFont(font)
        self.password_edit.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);")
        self.password_edit.setText("")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setPlaceholderText("")
        self.password_edit.setObjectName("password_edit")
        self.register_button = QtWidgets.QPushButton(self.centralwidget)
        self.register_button.setGeometry(QtCore.QRect(900, 420, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(True)
        self.register_button.setFont(font)
        self.register_button.setStyleSheet("QPushButton#register_button{\n"
"    border:none;\n"
"    color: rgb(29, 98, 168)\n"
"}\n"
"QPushButton#register_button:pressed{\n"
"    color:rgb(19, 38, 99)\n"
"}")
        self.register_button.setObjectName("register_button")
        self.forget_password_button = QtWidgets.QPushButton(self.centralwidget)
        self.forget_password_button.setGeometry(QtCore.QRect(930, 310, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(False)
        self.forget_password_button.setFont(font)
        self.forget_password_button.setStyleSheet("QPushButton#forget_password_button{\n"
"    border:none;\n"
"}\n"
"QPushButton#forget_password_button:pressed{\n"
"    color:rgb(19, 38, 99)\n"
"}")
        self.forget_password_button.setObjectName("forget_password_button")
        self.error_login = QtWidgets.QLabel(self.centralwidget)
        self.error_login.setGeometry(QtCore.QRect(640, 114, 421, 51))
        self.error_login.setStyleSheet("color:rgb(255,0,0)")
        self.error_login.setText("")
        self.error_login.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.error_login.setWordWrap(True)
        self.error_login.setObjectName("error_login")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 250, 291, 111))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Icon/Logo.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 571, 661))
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Icon/background 2.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.login_button.raise_()
        self.register_label.raise_()
        self.label_3.raise_()
        self.email_edit.raise_()
        self.label_7.raise_()
        self.password_edit.raise_()
        self.register_button.raise_()
        self.forget_password_button.raise_()
        self.error_login.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Realip"))
        self.label_2.setText(_translate("MainWindow", "Login"))
        self.login_button.setText(_translate("MainWindow", "Login"))
        self.register_label.setText(_translate("MainWindow", "Don\'t have an account?"))
        self.label_3.setText(_translate("MainWindow", "Email:"))
        self.label_7.setText(_translate("MainWindow", "Password:"))
        self.register_button.setText(_translate("MainWindow", "Register"))
        self.forget_password_button.setText(_translate("MainWindow", "Forget Password?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
