# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Profile_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1183, 653)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow#MainWindow{\n"
"    background-color:rgb(228, 235, 245);\n"
"    \n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 211, 651))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(255,255,255)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.notification_button = QtWidgets.QPushButton(self.centralwidget)
        self.notification_button.setGeometry(QtCore.QRect(0, 210, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.notification_button.setFont(font)
        self.notification_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.notification_button.setStyleSheet("QPushButton#notification_button{\n"
"    border:none;\n"
"    text-align: left;\n"
"    padding-left: 30px;\n"
"    color:rgb(52, 128, 235);\n"
"}\n"
"QPushButton#notification_button:hover{\n"
"    padding-left:40px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/notification_icon_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notification_button.setIcon(icon)
        self.notification_button.setIconSize(QtCore.QSize(35, 35))
        self.notification_button.setObjectName("notification_button")
        self.dashboard_button = QtWidgets.QPushButton(self.centralwidget)
        self.dashboard_button.setGeometry(QtCore.QRect(0, 269, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dashboard_button.setFont(font)
        self.dashboard_button.setStyleSheet("QPushButton#dashboard_button{\n"
"    color:rgb(52, 128, 235);\n"
"    border:none;\n"
"    background-color:rgb(255,255,255);\n"
"    text-align: left;\n"
"    padding-left: 30px;\n"
"}\n"
"QPushButton#dashboard_button:hover{\n"
"    padding-left:40px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icon/graph_icon_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboard_button.setIcon(icon1)
        self.dashboard_button.setIconSize(QtCore.QSize(35, 35))
        self.dashboard_button.setObjectName("dashboard_button")
        self.result_button = QtWidgets.QPushButton(self.centralwidget)
        self.result_button.setGeometry(QtCore.QRect(0, 328, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.result_button.setFont(font)
        self.result_button.setStyleSheet("QPushButton#result_button{\n"
"    border:none;\n"
"    text-align: left;\n"
"    padding-left: 30px;\n"
"    color:rgb(52, 128, 235);\n"
"    background-color:rgb(255, 255, 255)\n"
"}\n"
"QPushButton#result_button:hover{\n"
"    padding-left:40px;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icon/result_icon_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.result_button.setIcon(icon2)
        self.result_button.setIconSize(QtCore.QSize(35, 35))
        self.result_button.setObjectName("result_button")
        self.upload_video_button = QtWidgets.QPushButton(self.centralwidget)
        self.upload_video_button.setGeometry(QtCore.QRect(0, 387, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.upload_video_button.setFont(font)
        self.upload_video_button.setStyleSheet("QPushButton#upload_video_button{\n"
"    border:none;\n"
"    text-align: left;\n"
"    padding-left: 30px;\n"
"    color:rgb(52, 128, 235);\n"
"}\n"
"QPushButton#upload_video_button:hover{\n"
"    padding-left:40px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icon/upload_icon_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upload_video_button.setIcon(icon3)
        self.upload_video_button.setIconSize(QtCore.QSize(35, 35))
        self.upload_video_button.setObjectName("upload_video_button")
        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setGeometry(QtCore.QRect(0, 593, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.logout_button.setFont(font)
        self.logout_button.setStyleSheet("QPushButton#logout_button{\n"
"    border:none;\n"
"    text-align: left;\n"
"    padding-left: 30px;\n"
"    color:rgb(52, 128, 235);\n"
"}\n"
"QPushButton#logout_button:hover{\n"
"    padding-left:40px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icon/logout_icon_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_button.setIcon(icon4)
        self.logout_button.setIconSize(QtCore.QSize(35, 35))
        self.logout_button.setObjectName("logout_button")
        self.profile_button = QtWidgets.QPushButton(self.centralwidget)
        self.profile_button.setGeometry(QtCore.QRect(53, 95, 101, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.profile_button.setFont(font)
        self.profile_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.profile_button.setStyleSheet("QPushButton#profile_button{\n"
"    border:none;\n"
"}")
        self.profile_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icon/user_icon_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_button.setIcon(icon5)
        self.profile_button.setIconSize(QtCore.QSize(120, 120))
        self.profile_button.setObjectName("profile_button")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 30, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 931, 611))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius:15px;\n"
"background-color:rgb(255,255,255)")
        self.label_2.setText("")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.email_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.email_edit.setGeometry(QtCore.QRect(360, 130, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.email_edit.setFont(font)
        self.email_edit.setStyleSheet("border :1px outset gray;\n"
"border-radius: 5px;\n"
"padding-left: 10px;\n"
"")
        self.email_edit.setText("")
        self.email_edit.setReadOnly(True)
        self.email_edit.setPlaceholderText("")
        self.email_edit.setObjectName("email_edit")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(260, 80, 871, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 130, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 201, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setGeometry(QtCore.QRect(360, 201, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.name_edit.setFont(font)
        self.name_edit.setStyleSheet("border :1px outset gray;\n"
"border-radius: 5px;\n"
"padding-left: 10px;\n"
"")
        self.name_edit.setText("")
        self.name_edit.setReadOnly(True)
        self.name_edit.setPlaceholderText("")
        self.name_edit.setObjectName("name_edit")
        self.current_pass_label = QtWidgets.QLabel(self.centralwidget)
        self.current_pass_label.setGeometry(QtCore.QRect(680, 130, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.current_pass_label.setFont(font)
        self.current_pass_label.setObjectName("current_pass_label")
        self.new_pass_label = QtWidgets.QLabel(self.centralwidget)
        self.new_pass_label.setGeometry(QtCore.QRect(680, 201, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.new_pass_label.setFont(font)
        self.new_pass_label.setObjectName("new_pass_label")
        self.confirm_pass_label = QtWidgets.QLabel(self.centralwidget)
        self.confirm_pass_label.setGeometry(QtCore.QRect(680, 270, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_pass_label.setFont(font)
        self.confirm_pass_label.setObjectName("confirm_pass_label")
        self.current_pass_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.current_pass_edit.setGeometry(QtCore.QRect(840, 130, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.current_pass_edit.setFont(font)
        self.current_pass_edit.setStyleSheet("border :1px outset gray;\n"
"border-radius: 5px;\n"
"padding-left: 10px;\n"
"")
        self.current_pass_edit.setText("")
        self.current_pass_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.current_pass_edit.setPlaceholderText("")
        self.current_pass_edit.setObjectName("current_pass_edit")
        self.new_pass_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.new_pass_edit.setGeometry(QtCore.QRect(840, 201, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.new_pass_edit.setFont(font)
        self.new_pass_edit.setStyleSheet("border :1px outset gray;\n"
"border-radius: 5px;\n"
"padding-left: 10px;\n"
"")
        self.new_pass_edit.setText("")
        self.new_pass_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new_pass_edit.setPlaceholderText("")
        self.new_pass_edit.setObjectName("new_pass_edit")
        self.confirm_pass_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.confirm_pass_edit.setGeometry(QtCore.QRect(840, 270, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.confirm_pass_edit.setFont(font)
        self.confirm_pass_edit.setStyleSheet("border :1px outset gray;\n"
"border-radius: 5px;\n"
"padding-left: 10px;\n"
"")
        self.confirm_pass_edit.setText("")
        self.confirm_pass_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_pass_edit.setPlaceholderText("")
        self.confirm_pass_edit.setObjectName("confirm_pass_edit")
        self.edit_name_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_name_button.setGeometry(QtCore.QRect(623, 201, 31, 31))
        self.edit_name_button.setStyleSheet("border: none;")
        self.edit_name_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icon/edit_icon_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_name_button.setIcon(icon6)
        self.edit_name_button.setIconSize(QtCore.QSize(33, 34))
        self.edit_name_button.setObjectName("edit_name_button")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(950, 380, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.save_button.setFont(font)
        self.save_button.setStyleSheet("QPushButton#save_button{\n"
"    background-color:rgb(52, 128, 235);\n"
"    border:none;\n"
"    color:rgb(255,255,255);\n"
"    border-radius: 15px\n"
"}\n"
"QPushButton#save_button:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgb(19, 38, 99)\n"
"}")
        self.save_button.setAutoDefault(False)
        self.save_button.setObjectName("save_button")
        self.password_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_edit.setGeometry(QtCore.QRect(360, 270, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.password_edit.setFont(font)
        self.password_edit.setStyleSheet("border :1px outset gray;\n"
"border-radius: 5px;\n"
"padding-left: 10px;\n"
"")
        self.password_edit.setText("")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setReadOnly(True)
        self.password_edit.setPlaceholderText("")
        self.password_edit.setObjectName("password_edit")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(270, 270, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.edit_password_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_password_button.setGeometry(QtCore.QRect(623, 270, 31, 31))
        self.edit_password_button.setStyleSheet("border: none;")
        self.edit_password_button.setText("")
        self.edit_password_button.setIcon(icon6)
        self.edit_password_button.setIconSize(QtCore.QSize(33, 34))
        self.edit_password_button.setObjectName("edit_password_button")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(790, 380, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("QPushButton#cancel_button{\n"
"    border :2px solid gray;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton#cancel_button:pressed{\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"    border :2px solid black;\n"
"    background-color:rgb(0, 0, 0);\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.cancel_button.setAutoDefault(False)
        self.cancel_button.setObjectName("cancel_button")
        self.name_error = QtWidgets.QLabel(self.centralwidget)
        self.name_error.setGeometry(QtCore.QRect(360, 234, 261, 41))
        self.name_error.setStyleSheet("color:rgb(255,0,0)")
        self.name_error.setText("")
        self.name_error.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.name_error.setWordWrap(True)
        self.name_error.setObjectName("name_error")
        self.current_pass_error = QtWidgets.QLabel(self.centralwidget)
        self.current_pass_error.setGeometry(QtCore.QRect(840, 163, 261, 41))
        self.current_pass_error.setStyleSheet("color:rgb(255,0,0)")
        self.current_pass_error.setText("")
        self.current_pass_error.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.current_pass_error.setWordWrap(True)
        self.current_pass_error.setObjectName("current_pass_error")
        self.new_pass_error = QtWidgets.QLabel(self.centralwidget)
        self.new_pass_error.setGeometry(QtCore.QRect(840, 234, 261, 41))
        self.new_pass_error.setStyleSheet("color:rgb(255,0,0)")
        self.new_pass_error.setText("")
        self.new_pass_error.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.new_pass_error.setWordWrap(True)
        self.new_pass_error.setObjectName("new_pass_error")
        self.confirm_pass_error = QtWidgets.QLabel(self.centralwidget)
        self.confirm_pass_error.setGeometry(QtCore.QRect(840, 303, 261, 41))
        self.confirm_pass_error.setStyleSheet("color:rgb(255,0,0)")
        self.confirm_pass_error.setText("")
        self.confirm_pass_error.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.confirm_pass_error.setWordWrap(True)
        self.confirm_pass_error.setObjectName("confirm_pass_error")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(24, 13, 161, 51))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Icon/Logo.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_2.raise_()
        self.label.raise_()
        self.notification_button.raise_()
        self.dashboard_button.raise_()
        self.result_button.raise_()
        self.upload_video_button.raise_()
        self.logout_button.raise_()
        self.profile_button.raise_()
        self.label_3.raise_()
        self.email_edit.raise_()
        self.line.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.name_edit.raise_()
        self.current_pass_label.raise_()
        self.new_pass_label.raise_()
        self.confirm_pass_label.raise_()
        self.current_pass_edit.raise_()
        self.new_pass_edit.raise_()
        self.confirm_pass_edit.raise_()
        self.edit_name_button.raise_()
        self.save_button.raise_()
        self.password_edit.raise_()
        self.label_9.raise_()
        self.edit_password_button.raise_()
        self.cancel_button.raise_()
        self.name_error.raise_()
        self.current_pass_error.raise_()
        self.new_pass_error.raise_()
        self.confirm_pass_error.raise_()
        self.label_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.notification_button.setText(_translate("MainWindow", "Notification"))
        self.dashboard_button.setText(_translate("MainWindow", "Dashboard"))
        self.result_button.setText(_translate("MainWindow", "Result"))
        self.upload_video_button.setText(_translate("MainWindow", "Upload Video"))
        self.logout_button.setText(_translate("MainWindow", "Logout"))
        self.label_3.setText(_translate("MainWindow", "My Profile"))
        self.label_4.setText(_translate("MainWindow", "Email:"))
        self.label_5.setText(_translate("MainWindow", "Full Name:"))
        self.current_pass_label.setText(_translate("MainWindow", "Current Password:"))
        self.new_pass_label.setText(_translate("MainWindow", "New Password:"))
        self.confirm_pass_label.setText(_translate("MainWindow", "Confirm Password:"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.label_9.setText(_translate("MainWindow", "Password:"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
