# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1183, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(640, 60, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 0, 611, 651))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(255,255,255)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.email_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.email_edit.setGeometry(QtCore.QRect(640, 190, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.email_edit.setFont(font)
        self.email_edit.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);")
        self.email_edit.setText("")
        self.email_edit.setPlaceholderText("")
        self.email_edit.setObjectName("email_edit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(640, 170, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.register_button = QtWidgets.QPushButton(self.centralwidget)
        self.register_button.setGeometry(QtCore.QRect(770, 475, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.register_button.setFont(font)
        self.register_button.setStyleSheet("QPushButton#register_button{\n"
"    background-color:rgb(52, 128, 235);\n"
"    border:none;\n"
"    color:rgb(255,255,255);\n"
"    border-radius: 15px\n"
"}\n"
"QPushButton#register_button:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgb(19, 38, 99)\n"
"}")
        self.register_button.setAutoDefault(False)
        self.register_button.setObjectName("register_button")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(750, 527, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(640, 248, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.full_name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.full_name_edit.setGeometry(QtCore.QRect(640, 268, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.full_name_edit.setFont(font)
        self.full_name_edit.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);")
        self.full_name_edit.setText("")
        self.full_name_edit.setPlaceholderText("")
        self.full_name_edit.setObjectName("full_name_edit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(640, 322, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.password_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_edit.setGeometry(QtCore.QRect(640, 342, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.password_edit.setFont(font)
        self.password_edit.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);")
        self.password_edit.setText("")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setPlaceholderText("")
        self.password_edit.setObjectName("password_edit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(640, 396, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.confirm_password_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.confirm_password_edit.setGeometry(QtCore.QRect(640, 416, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.confirm_password_edit.setFont(font)
        self.confirm_password_edit.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);")
        self.confirm_password_edit.setText("")
        self.confirm_password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_password_edit.setPlaceholderText("")
        self.confirm_password_edit.setObjectName("confirm_password_edit")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(920, 527, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(True)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("QPushButton#login_button{\n"
"    border:none;\n"
"    color: rgb(29, 98, 168)\n"
"}\n"
"QPushButton#login_button:pressed{\n"
"    color:rgb(19, 38, 99)\n"
"}")
        self.login_button.setObjectName("login_button")
        self.error_email = QtWidgets.QLabel(self.centralwidget)
        self.error_email.setGeometry(QtCore.QRect(640, 222, 421, 16))
        self.error_email.setStyleSheet("color:rgb(255,0,0)")
        self.error_email.setText("")
        self.error_email.setObjectName("error_email")
        self.error_name = QtWidgets.QLabel(self.centralwidget)
        self.error_name.setGeometry(QtCore.QRect(640, 298, 421, 16))
        self.error_name.setStyleSheet("color:rgb(255,0,0)")
        self.error_name.setText("")
        self.error_name.setObjectName("error_name")
        self.error_pass = QtWidgets.QLabel(self.centralwidget)
        self.error_pass.setGeometry(QtCore.QRect(640, 373, 421, 16))
        self.error_pass.setStyleSheet("color:rgb(255,0,0)")
        self.error_pass.setText("")
        self.error_pass.setObjectName("error_pass")
        self.error_con_pass = QtWidgets.QLabel(self.centralwidget)
        self.error_con_pass.setGeometry(QtCore.QRect(640, 450, 421, 16))
        self.error_con_pass.setStyleSheet("color:rgb(255,0,0)")
        self.error_con_pass.setText("")
        self.error_con_pass.setObjectName("error_con_pass")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 571, 661))
        self.label_8.setStyleSheet("")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("Icon/background 2.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 250, 291, 111))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Icon/Logo.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label.raise_()
        self.label_2.raise_()
        self.email_edit.raise_()
        self.label_3.raise_()
        self.register_button.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.full_name_edit.raise_()
        self.label_5.raise_()
        self.password_edit.raise_()
        self.label_7.raise_()
        self.confirm_password_edit.raise_()
        self.login_button.raise_()
        self.error_email.raise_()
        self.error_name.raise_()
        self.error_pass.raise_()
        self.error_con_pass.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Register an account"))
        self.label_3.setText(_translate("MainWindow", "Email:"))
        self.register_button.setText(_translate("MainWindow", "Register"))
        self.label_6.setText(_translate("MainWindow", "Already have an account?"))
        self.label_4.setText(_translate("MainWindow", "Full Name:"))
        self.label_5.setText(_translate("MainWindow", "Password:"))
        self.label_7.setText(_translate("MainWindow", "Confirm Password:"))
        self.login_button.setText(_translate("MainWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
