# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Verification_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1183, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(640, 60, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 0, 611, 651))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(255,255,255)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.confirm_button = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_button.setGeometry(QtCore.QRect(860, 300, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_button.setFont(font)
        self.confirm_button.setStyleSheet("QPushButton#confirm_button{\n"
"    background-color:rgb(52, 128, 235);\n"
"    border:none;\n"
"    color:rgb(255,255,255);\n"
"    border-radius: 15px\n"
"}\n"
"QPushButton#confirm_button:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgb(19, 38, 99)\n"
"}")
        self.confirm_button.setAutoDefault(False)
        self.confirm_button.setObjectName("confirm_button")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(640, 190, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.otp_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.otp_edit.setGeometry(QtCore.QRect(640, 210, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.otp_edit.setFont(font)
        self.otp_edit.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);")
        self.otp_edit.setText("")
        self.otp_edit.setPlaceholderText("")
        self.otp_edit.setObjectName("otp_edit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(640, 112, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.error_otp = QtWidgets.QLabel(self.centralwidget)
        self.error_otp.setGeometry(QtCore.QRect(640, 244, 421, 16))
        self.error_otp.setStyleSheet("color:rgb(255,0,0)")
        self.error_otp.setText("")
        self.error_otp.setObjectName("error_otp")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(640, 300, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.back_button.setFont(font)
        self.back_button.setStyleSheet("QPushButton#back_button{\n"
"    border :2px solid gray;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton#back_button:pressed{\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"    border :2px solid black;\n"
"    background-color:rgb(0, 0, 0);\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.back_button.setAutoDefault(False)
        self.back_button.setObjectName("back_button")
        self.register_label = QtWidgets.QLabel(self.centralwidget)
        self.register_label.setGeometry(QtCore.QRect(727, 360, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.register_label.setFont(font)
        self.register_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.register_label.setObjectName("register_label")
        self.resend_otp_button = QtWidgets.QPushButton(self.centralwidget)
        self.resend_otp_button.setGeometry(QtCore.QRect(888, 360, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(True)
        self.resend_otp_button.setFont(font)
        self.resend_otp_button.setStyleSheet("QPushButton#resend_otp_button{\n"
"    border:none;\n"
"    color: rgb(29, 98, 168)\n"
"}\n"
"QPushButton#resend_otp_button:pressed{\n"
"    color:rgb(0, 0, 0)\n"
"}")
        self.resend_otp_button.setObjectName("resend_otp_button")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 250, 291, 111))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Icon/Logo.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 571, 661))
        self.label_8.setStyleSheet("")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("Icon/background 2.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label.raise_()
        self.label_2.raise_()
        self.confirm_button.raise_()
        self.label_3.raise_()
        self.otp_edit.raise_()
        self.label_4.raise_()
        self.error_otp.raise_()
        self.back_button.raise_()
        self.register_label.raise_()
        self.resend_otp_button.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Verification Code"))
        self.confirm_button.setText(_translate("MainWindow", "Confirm"))
        self.label_3.setText(_translate("MainWindow", "OTP:"))
        self.label_4.setText(_translate("MainWindow", "We have sent a verification code to your email address. Please check your email."))
        self.back_button.setText(_translate("MainWindow", "Back"))
        self.register_label.setText(_translate("MainWindow", "Didn\'t receive the code?"))
        self.resend_otp_button.setText(_translate("MainWindow", "Resend OTP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
